-- Guard the reviewed baseline against concurrent editorial changes.
-- D1 applies a migration transactionally; a failed CHECK prevents publication.
CREATE TABLE _a1_release_083_guard (ok INTEGER NOT NULL CHECK (ok = 1));
INSERT INTO _a1_release_083_guard SELECT CASE WHEN
(SELECT COUNT(*) FROM texts WHERE level='A1' AND display_order=5 AND title='Мій звичайний день' AND json(paragraphs_json)=json('["Я прокидаюся о сьомій годині і не поспішаю вставати. Потім я йду у ванну кімнату, мию обличчя і чищу зуби. На кухні я їм кашу і п''ю теплий чай. Після сніданку я перевіряю сумку і беру ключі.","До школи я йду пішки. На уроках я слухаю вчителя, читаю текст і пишу в зошиті. На перерві я їм яблуко і говорю з другом. Ми часто говоримо про футбол або домашнє завдання. Після школи я повертаюся додому.","Удома я обідаю і трохи відпочиваю. Потім я роблю домашнє завдання, гуляю з другом і вечеряю з родиною. Перед сном я кладу книжки в сумку і ставлю будильник. Якщо я все готую ввечері, ранок проходить легко."]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=5))=5 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=5) AND display_order=1 AND prompt='Коли герой прокидається?' AND correct_answer='О сьомій годині' AND json(wrong_answers_json)=json('["О десятій годині","Опівночі","О першій годині"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=5) AND display_order=2 AND prompt='Що герой їсть на перерві?' AND correct_answer='Яблуко' AND json(wrong_answers_json)=json('["Млинці","Суп","Морозиво"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=5) AND display_order=3 AND prompt='Куди герой йде після уроків?' AND correct_answer='Додому' AND json(wrong_answers_json)=json('["На пошту","До моря","В автосалон"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=5) AND display_order=4 AND prompt='Що герой робить увечері?' AND correct_answer='Гуляє з другом' AND json(wrong_answers_json)=json('["Купує машину","Малює квіти","Пише лист"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=5) AND display_order=5 AND prompt='Що герой ставить перед сном?' AND correct_answer='Будильник' AND json(wrong_answers_json)=json('["Чайник","Тарілку","Стілець"]'))=1
AND (SELECT COUNT(*) FROM texts WHERE level='A1' AND display_order=8 AND title='Моя м''яка іграшка' AND json(paragraphs_json)=json('["У мене є улюблена м''яка іграшка. Це коричневий ведмедик, якого звати Тедді. У нього круглі вуха, чорні очі і дуже м''які лапи. Він невеликий, тому я легко беру його з собою.","Тедді сидить на моєму ліжку майже весь день. Увечері я беру його в руки, читаю книжку і відпочиваю. Коли мені сумно, ведмедик завжди лежить поруч.","Мама подарувала мені Тедді на день народження. Іграшка вже не нова, але вона дуже дорога для мене. Я часто ставлю Тедді на подушку і кажу йому добраніч."]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=8))=5 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=8) AND display_order=1 AND prompt='Яка м''яка іграшка є в героя?' AND correct_answer='Ведмедик' AND json(wrong_answers_json)=json('["Лялька","Машина","Кубик"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=8) AND display_order=2 AND prompt='Як звати ведмедика?' AND correct_answer='Тедді' AND json(wrong_answers_json)=json('["Мурчик","Бім","Данило"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=8) AND display_order=3 AND prompt='Де сидить ведмедик?' AND correct_answer='На ліжку' AND json(wrong_answers_json)=json('["У дворі","У машині","На пошті"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=8) AND display_order=4 AND prompt='Хто подарував ведмедика?' AND correct_answer='Мама' AND json(wrong_answers_json)=json('["Тато","Учитель","Сусід"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=8) AND display_order=5 AND prompt='Який ведмедик?' AND correct_answer='Коричневий і м''який' AND json(wrong_answers_json)=json('["Білий і швидкий","Новий і холодний","Червоний і твердий"]'))=1
AND (SELECT COUNT(*) FROM texts WHERE level='A1' AND display_order=9 AND title='Моя чудова родина' AND json(paragraphs_json)=json('["У мене є чудова родина. Моя мама добра і спокійна, вона готує сніданок і часто читає книжки. Мій тато веселий, він працює в офісі і любить музику.","У мене є сестра Ліза. Вона ходить до школи і любить малювати квіти. Ще у нас є дідусь, який часто розповідає цікаві історії. У неділю він приходить до нас на обід.","Увечері ми сидимо разом на кухні. Ми п''ємо чай, говоримо про день і сміємося. Ліза показує малюнок, тато слухає, а мама усміхається. Я дуже люблю свою родину. Коли мені потрібна допомога, родина завжди поруч. Тому вдома мені легко і тепло."]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=9))=5 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=9) AND display_order=1 AND prompt='Яка родина у героя?' AND correct_answer='Чудова' AND json(wrong_answers_json)=json('["Мала і сумна","Нова","Далека"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=9) AND display_order=2 AND prompt='Що робить мама?' AND correct_answer='Готує сніданок і читає книжки' AND json(wrong_answers_json)=json('["Водить машину","Продає марки","Грає в шахи"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=9) AND display_order=3 AND prompt='Як звати сестру?' AND correct_answer='Ліза' AND json(wrong_answers_json)=json('["Оля","Софійка","Марта"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=9) AND display_order=4 AND prompt='Що любить Ліза?' AND correct_answer='Малювати квіти' AND json(wrong_answers_json)=json('["Купувати машини","Писати адресу","Годувати кота"]'))=1 AND (SELECT COUNT(*) FROM questions WHERE story_id=(SELECT id FROM texts WHERE level='A1' AND display_order=9) AND display_order=5 AND prompt='Що сім''я робить увечері?' AND correct_answer='П''є чай і говорить' AND json(wrong_answers_json)=json('["Йде до школи","Купує корм","Їде до моря"]'))=1
AND (SELECT COUNT(*) FROM texts WHERE level='A1' AND display_order=15)=0
AND (SELECT COUNT(*) FROM texts WHERE level='A1' AND display_order=16)=0
AND (SELECT COUNT(*) FROM texts WHERE level='A1' AND display_order=17)=0
AND (SELECT COUNT(*) FROM texts WHERE level='A1' AND display_order=18)=0
AND (SELECT COUNT(*) FROM texts WHERE level='A1' AND display_order=19)=0
THEN 1 ELSE 0 END;
DROP TABLE _a1_release_083_guard;

-- Generated by scripts/build-content-refresh.mjs.
-- Brings texts and questions up to date with data/content-seed.json.
--
-- Upserts on UNIQUE(level, display_order). Existing rows keep their id,
-- is_enabled, question_index, drafts and editor history; only the content
-- columns are overwritten. Questions are replaced per story, never with a
-- table-wide DELETE. Rows that exist live but not in the seed are left alone.
-- Re-running this migration is a no-op beyond refreshing updated_at.

INSERT INTO texts (level, display_order, title, paragraphs_json, show_word_count, is_enabled, question_index) VALUES ('A1', 5, 'Мій звичайний день', '["Я прокидаюся о сьомій годині і не поспішаю вставати. Потім я йду у ванну кімнату, мию обличчя і чищу зуби. На кухні я їм кашу і п''ю теплий чай. Після сніданку я перевіряю сумку і беру ключі.","До школи я йду пішки. На уроках я слухаю вчителя, читаю текст і пишу в зошиті. На перерві я їм яблуко і говорю з другом. Ми часто говоримо про футбол або домашнє завдання. Після школи я повертаюся додому.","Удома я обідаю і трохи відпочиваю. Потім я роблю домашнє завдання, гуляю з другом і вечеряю з родиною. Перед сном я кладу книжки в сумку і ставлю будильник. Я все готую ввечері, тому ранок проходить легко."]', 1, 1, 5) ON CONFLICT(level, display_order) DO UPDATE SET title = excluded.title, paragraphs_json = excluded.paragraphs_json, show_word_count = excluded.show_word_count, updated_at = CURRENT_TIMESTAMP;
DELETE FROM questions WHERE story_id = (SELECT id FROM texts WHERE level = 'A1' AND display_order = 5);
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 5), 1, 'Коли герой прокидається?', 'О сьомій годині', '["О десятій годині","Опівночі","О першій годині"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 5), 2, 'Що герой їсть на перерві?', 'Яблуко', '["Млинці","Суп","Морозиво"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 5), 3, 'Куди герой йде після уроків?', 'Додому', '["На пошту","До моря","В автосалон"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 5), 4, 'Що герой робить увечері?', 'Гуляє з другом', '["Купує машину","Малює квіти","Пише лист"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 5), 5, 'Що герой ставить перед сном?', 'Будильник', '["Чайник","Тарілку","Стілець"]');
INSERT INTO texts (level, display_order, title, paragraphs_json, show_word_count, is_enabled, question_index) VALUES ('A1', 8, 'Моя м''яка іграшка', '["У мене є улюблена м''яка іграшка. Це коричневий ведмедик. Його звати Тедді. У нього круглі вуха, чорні очі і дуже м''які лапи. Він невеликий, тому я легко беру його з собою.","Тедді сидить на моєму ліжку майже весь день. Увечері я беру його в руки, читаю книжку і відпочиваю. Коли мені сумно, ведмедик завжди лежить поруч.","Мама подарувала мені Тедді на день народження. Іграшка вже не нова, але вона дуже дорога для мене. Я часто ставлю Тедді на подушку і кажу йому добраніч."]', 1, 1, 8) ON CONFLICT(level, display_order) DO UPDATE SET title = excluded.title, paragraphs_json = excluded.paragraphs_json, show_word_count = excluded.show_word_count, updated_at = CURRENT_TIMESTAMP;
DELETE FROM questions WHERE story_id = (SELECT id FROM texts WHERE level = 'A1' AND display_order = 8);
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 8), 1, 'Яка м''яка іграшка є в героя?', 'Ведмедик', '["Лялька","Машина","Кубик"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 8), 2, 'Як звати ведмедика?', 'Тедді', '["Мурчик","Бім","Данило"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 8), 3, 'Де сидить ведмедик?', 'На ліжку', '["У дворі","У машині","На пошті"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 8), 4, 'Хто подарував ведмедика?', 'Мама', '["Тато","Учитель","Сусід"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 8), 5, 'Який ведмедик?', 'Коричневий і м''який', '["Білий і швидкий","Новий і холодний","Червоний і твердий"]');
INSERT INTO texts (level, display_order, title, paragraphs_json, show_word_count, is_enabled, question_index) VALUES ('A1', 9, 'Моя чудова родина', '["У мене є чудова родина. Моя мама добра і спокійна, вона готує сніданок і часто читає книжки. Мій тато веселий, він працює в офісі і любить музику.","У мене є сестра Ліза. Вона ходить до школи і любить малювати квіти. Ще у нас є дідусь. Він часто розповідає цікаві історії. У неділю він приходить до нас на обід.","Увечері ми сидимо разом на кухні. Ми п''ємо чай, говоримо про день і сміємося. Ліза показує малюнок, тато слухає, а мама усміхається. Я дуже люблю свою родину. Коли мені потрібна допомога, родина завжди поруч. Тому вдома мені легко і тепло."]', 1, 1, 9) ON CONFLICT(level, display_order) DO UPDATE SET title = excluded.title, paragraphs_json = excluded.paragraphs_json, show_word_count = excluded.show_word_count, updated_at = CURRENT_TIMESTAMP;
DELETE FROM questions WHERE story_id = (SELECT id FROM texts WHERE level = 'A1' AND display_order = 9);
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 9), 1, 'Яка родина у героя?', 'Чудова', '["Мала і сумна","Нова","Далека"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 9), 2, 'Що робить мама?', 'Готує сніданок і читає книжки', '["Водить машину","Продає марки","Грає в шахи"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 9), 3, 'Як звати сестру?', 'Ліза', '["Оля","Софійка","Марта"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 9), 4, 'Що любить Ліза?', 'Малювати квіти', '["Купувати машини","Писати адресу","Годувати кота"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 9), 5, 'Що сім''я робить увечері?', 'П''є чай і говорить', '["Йде до школи","Купує корм","Їде до моря"]');
INSERT INTO texts (level, display_order, title, paragraphs_json, show_word_count, is_enabled, question_index) VALUES ('A1', 15, 'Моя кімната', '["У моїй невеликій кімнаті є велике вікно. З вікна я бачу зелені дерева і доріжку біля дому. Уранці тут світло. Біля вікна стоїть письмовий стіл, а поруч є стілець.","На моєму столі я пишу лист для тітки. Потім кладу ручку в маленьку коробку біля книжок. Книжки стоять на полиці над столом. Під ліжком я тримаю взуття для прогулянок. На вихідних я також прибираю тут після роботи.","Увечері я вмикаю лампу і сідаю на ліжко. Я читаю кілька сторінок і дивлюся на годинник. Уже пізно. Перед сном я ставлю будильник і вимикаю лампу."]', 1, 1, 15) ON CONFLICT(level, display_order) DO UPDATE SET title = excluded.title, paragraphs_json = excluded.paragraphs_json, show_word_count = excluded.show_word_count, updated_at = CURRENT_TIMESTAMP;
DELETE FROM questions WHERE story_id = (SELECT id FROM texts WHERE level = 'A1' AND display_order = 15);
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 15), 1, 'Що видно з вікна?', 'Дерева і доріжку', '["Річку і міст","Школу і магазин","Море і пляж"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 15), 2, 'Для кого автор пише лист?', 'Для тітки', '["Для бабусі","Для брата","Для друга"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 15), 3, 'Де стоять книжки?', 'На полиці', '["У шафі","На підлозі","На дивані"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 15), 4, 'Що лежить під ліжком?', 'Взуття', '["М''яч","Килим","Іграшки"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 15), 5, 'Що автор робить після читання?', 'Дивиться на годинник', '["Слухає музику","Малює картину","Телефонує мамі"]');
INSERT INTO texts (level, display_order, title, paragraphs_json, show_word_count, is_enabled, question_index) VALUES ('A1', 16, 'У школі', '["У нашому класі великі вікна, тому тут світло. Я сиджу з подругою Олею за першою партою. На парті лежать зошит, книжка і дві нові ручки. Починається наш урок української мови. У класі тихо. Я готова.","Учителька стоїть біля дошки і читає короткий текст. Я уважно слухаю і пишу нові слова в зошиті. Я питаю вчительку:\n— Ви можете повторити слово? Потім питаю Олю:\n— Ти маєш ручку? Вона дає мені синю ручку.","Тепер я читаю текст уголос. Оля слухає мене і показує малюнок у книжці. Це моя улюблена частина уроку. Дзвонить дзвінок, і починається перерва. Потім ми виходимо в коридор і трохи відпочиваємо."]', 1, 1, 16) ON CONFLICT(level, display_order) DO UPDATE SET title = excluded.title, paragraphs_json = excluded.paragraphs_json, show_word_count = excluded.show_word_count, updated_at = CURRENT_TIMESTAMP;
DELETE FROM questions WHERE story_id = (SELECT id FROM texts WHERE level = 'A1' AND display_order = 16);
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 16), 1, 'З ким сидить авторка?', 'З Олею', '["З Лізою","З Мартою","З Софійкою"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 16), 2, 'Де стоїть учителька?', 'Біля дошки', '["Біля шафи","Біля дверей","Біля вікна"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 16), 3, 'Що авторка пише?', 'Нові слова', '["Свій розклад","Назви квітів","Імена друзів"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 16), 4, 'Що дає Оля?', 'Синю ручку', '["Червоний олівець","Жовтий пенал","Білий папір"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 16), 5, 'Куди діти йдуть на перерві?', 'У коридор', '["У двір","У сад","У їдальню"]');
INSERT INTO texts (level, display_order, title, paragraphs_json, show_word_count, is_enabled, question_index) VALUES ('A1', 17, 'Мій друг', '["Мого друга звати Андрій. Ми знаємо один одного вже п''ять років. Андрій живе біля парку і працює в магазині. Він високий і веселий. У нього є старий велосипед і великий чорний рюкзак.","У суботу ми зустрічаємося біля входу в парк. Спочатку гуляємо, а потім граємо в шахи. Андрій добре грає і пояснює мені кожний хід. Я слухаю його і думаю. Наша гра йде повільно.","Іноді я прошу друга допомогти з велосипедом. Андрій перевіряє колеса, а я тримаю велосипед. Потім ми разом їдемо додому. Я дуже радий такому доброму другові. Ми домовляємося знову грати в суботу."]', 1, 1, 17) ON CONFLICT(level, display_order) DO UPDATE SET title = excluded.title, paragraphs_json = excluded.paragraphs_json, show_word_count = excluded.show_word_count, updated_at = CURRENT_TIMESTAMP;
DELETE FROM questions WHERE story_id = (SELECT id FROM texts WHERE level = 'A1' AND display_order = 17);
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 17), 1, 'Як звати друга?', 'Андрій', '["Данило","Максим","Богдан"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 17), 2, 'Скільки років знайомі друзі?', 'П''ять', '["Два","Три","Чотири"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 17), 3, 'У що друзі грають?', 'У шахи', '["У футбол","У теніс","У баскетбол"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 17), 4, 'Що Андрій перевіряє?', 'Колеса', '["Двері","Вікна","Фари"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 17), 5, 'Що друзі роблять потім?', 'Їдуть додому', '["Ідуть на пошту","Готують вечерю","Читають газету"]');
INSERT INTO texts (level, display_order, title, paragraphs_json, show_word_count, is_enabled, question_index) VALUES ('A1', 18, 'Сніданок удома', '["На кухні вже сидить моя сестра. Вона ставить на стіл дві тарілки і чашки. Я кладу на стіл хліб, сир і помідор. Сестра ріже хліб, а я мию помідор. Усе готове. Ми сідаємо біля вікна і бажаємо одна одній смачного.","Я їм хліб і сир та п''ю чай. Сестра теж п''є чай, але їсть помідор. За сніданком ми завжди слухаємо тиху музику. Потім я мию чашки і ставлю їх на полицю. Час іти. Я виходжу з кухні та беру сумку для роботи."]', 1, 1, 18) ON CONFLICT(level, display_order) DO UPDATE SET title = excluded.title, paragraphs_json = excluded.paragraphs_json, show_word_count = excluded.show_word_count, updated_at = CURRENT_TIMESTAMP;
DELETE FROM questions WHERE story_id = (SELECT id FROM texts WHERE level = 'A1' AND display_order = 18);
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 18), 1, 'З ким снідає авторка?', 'Із сестрою', '["З мамою","З братом","Із сусідкою"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 18), 2, 'Хто ріже хліб?', 'Сестра', '["Мама","Бабуся","Тітка"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 18), 3, 'Що їсть авторка?', 'Хліб і сир', '["Кашу з молоком","Яйце з огірком","Булку з маслом"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 18), 4, 'Що слухають за сніданком?', 'Тиху музику', '["Ранкові новини","Коротку казку","Розмову про спорт"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 18), 5, 'Що авторка робить після їжі?', 'Миє чашки', '["Прибирає кімнату","Гуляє з собакою","Пише повідомлення"]');
INSERT INTO texts (level, display_order, title, paragraphs_json, show_word_count, is_enabled, question_index) VALUES ('A1', 19, 'У магазині', '["Покупець: — Добрий день! Дайте, будь ласка, хліб і молоко. Ще мені потрібні яблука для родини.\nПродавчиня: — Добрий день! Ось свіжий хліб, а поруч молоко. Ви хочете червоні яблука чи зелені?\nПокупець: — Червоні, будь ласка. Я беру три яблука. Скільки коштує хліб? Ви маєте маленький пакет?\nПродавчиня: — Хліб коштує двадцять гривень. Так, ось пакет для вас. Ви можете платити карткою.\nПокупець: — Добре, я плачу карткою. Дякую вам за допомогу! У вас завжди гарний хліб.\nПродавчиня: — Дякую! Приходьте до нас знову. Гарного вам дня!\nЯ беру пакет із покупками і виходжу з магазину."]', 1, 1, 19) ON CONFLICT(level, display_order) DO UPDATE SET title = excluded.title, paragraphs_json = excluded.paragraphs_json, show_word_count = excluded.show_word_count, updated_at = CURRENT_TIMESTAMP;
DELETE FROM questions WHERE story_id = (SELECT id FROM texts WHERE level = 'A1' AND display_order = 19);
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 19), 1, 'Що просить покупець спочатку?', 'Хліб і молоко', '["Сир і масло","Рис і рибу","Каву і печиво"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 19), 2, 'Які яблука бере покупець?', 'Червоні', '["Зелені","Жовті","Маленькі"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 19), 3, 'Скільки коштує хліб?', 'Двадцять гривень', '["Десять гривень","Тридцять гривень","Сорок гривень"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 19), 4, 'Як платить покупець?', 'Карткою', '["Монетами","Паперовими грошима","Телефоном"]');
INSERT INTO questions (story_id, display_order, prompt, correct_answer, wrong_answers_json) VALUES ((SELECT id FROM texts WHERE level = 'A1' AND display_order = 19), 5, 'Що покупець робить потім?', 'Виходить із магазину', '["Сідає біля каси","Говорить із другом","Шукає ще один товар"]');
