-- Polish dictionary update to the 2026-09-25 source, prepared by scripts/dictionary/prepare-update.mjs.
-- Adds story-word entries no earlier migration contains; existing rows are never replaced.
-- Generated by scripts/dictionary/build-dictionary-seed.mjs.
-- Source: Polish Wiktionary via Kaikki.org, snapshot 2026-09-25.
-- Scope: story.
-- Word forms: none of its own; the shared forms lead to each entry by lemma and part of speech.
-- Filed as English Wiktionary does: «той» pron as determiner.
-- Filed as English Wiktionary does: «десять» adj as numeral.
-- Filed as English Wiktionary does: «скільки» pron as determiner.
-- Filed as English Wiktionary does: «багато» num as determiner.
-- Filed as English Wiktionary does: «три» adj as numeral.
-- Filed as English Wiktionary does: «сто» adj as numeral.
-- Filed as English Wiktionary does: «не» particle as adverb.
-- Filed as English Wiktionary does: «два» adj as numeral.
-- Filed as English Wiktionary does: «ще» particle as adverb.
-- Filed as English Wiktionary does: «один» adj as numeral.
-- Filed as English Wiktionary does: «один» pron as numeral.
-- Filed as English Wiktionary does: «один» adj as numeral.
-- Filed as English Wiktionary does: «чотири» adj as numeral.
-- Filed as English Wiktionary does: «п'ять» adj as numeral.
-- Filed as English Wiktionary does: «сім» adj as numeral.
-- Filed as English Wiktionary does: «уже» particle as adverb.
-- Filed as English Wiktionary does: «навіть» particle as adverb.
-- Filed as English Wiktionary does: «цей» pron as determiner.
-- Filed as English Wiktionary does: «сорок» adj as numeral.
-- Filed as English Wiktionary does: «тільки» particle as adverb.
-- Filed as English Wiktionary does: «тільки» conj as adverb.
-- Filed as English Wiktionary does: «дев'ять» adj as numeral.
-- Filed as English Wiktionary does: «лише» particle as adverb.
-- Filed as English Wiktionary does: «лише» conj as adverb.
-- Filed as English Wiktionary does: «ні» particle as adverb.
-- Filed as English Wiktionary does: «ні» conj as adverb.
-- Filed as English Wiktionary does: «аж» particle as adverb.
-- Filed as English Wiktionary does: «аж» conj as adverb.
-- Filed as English Wiktionary does: «дванадцять» adj as numeral.
-- Filed as English Wiktionary does: «п'ятнадцять» adj as numeral.
-- Filed as English Wiktionary does: «восьмеро» num as determiner.
-- Filed as English Wiktionary does: «шістнадцять» adj as numeral.
-- Filed as English Wiktionary does: «двадцять» adj as numeral.
-- Filed as English Wiktionary does: «тридцять» adj as numeral.
-- Filed as English Wiktionary does: «кілька» num as determiner.
-- Filed as English Wiktionary does: «кожен» pron as adjective.
-- Filed as English Wiktionary does: «інший» pron as adjective.
-- Filed as English Wiktionary does: «тобто» conj as adverb.
-- Filed as English Wiktionary does: «тобто» particle as adverb.
-- Filed as English Wiktionary does: «мабуть» particle as adverb.

INSERT INTO dictionary_language_pairs (source_language, target_language, enabled, source_name, source_url, source_revision, license_name, license_url) VALUES ('uk', 'pl', 1, 'Polish Wiktionary via Kaikki.org', 'https://kaikki.org/plwiktionary/j%C4%99zyk%20ukrai%C5%84ski/', '2026-09-25', 'CC BY-SA 4.0 / GFDL', 'https://pl.wiktionary.org/wiki/Wikis%C5%82ownik:Prawa_autorskie') ON CONFLICT(source_language, target_language) DO UPDATE SET enabled = excluded.enabled, source_name = excluded.source_name, source_url = excluded.source_url, source_revision = excluded.source_revision, license_name = excluded.license_name, license_url = excluded.license_url;
INSERT OR IGNORE INTO dictionary_lexemes (id, source_language, lemma, normalized_lemma, part_of_speech, source_entry_id, source_id) VALUES ('lex_b89519c0c146ed98e90f05b7', 'uk', 'смачного', 'смачного', 'intj', 'raw:entry_2198ffe800cca847555834f7', 'kaikki-plwiktionary');
INSERT OR IGNORE INTO dictionary_senses (id, lexeme_id, sense_order, usage_tags_json) VALUES ('sense_b89519c0c146ed98e90f05b7', 'lex_b89519c0c146ed98e90f05b7', 1, '[]');
INSERT OR IGNORE INTO dictionary_translations (sense_id, target_language, translation, translation_order, source_id) VALUES ('sense_b89519c0c146ed98e90f05b7', 'pl', 'smacznego!', 1, 'kaikki-plwiktionary');
INSERT OR IGNORE INTO dictionary_lexemes (id, source_language, lemma, normalized_lemma, part_of_speech, source_entry_id, source_id) VALUES ('lex_3a473164143d32dfba543775', 'uk', 'десятий', 'десятий', 'adj', 'raw:entry_9ba46462d07da3e189231197', 'kaikki-plwiktionary');
INSERT OR IGNORE INTO dictionary_lexemes (id, source_language, lemma, normalized_lemma, part_of_speech, source_entry_id, source_id) VALUES ('lex_bd574cd80c059b2643e7caa5', 'uk', 'заплатити', 'заплатити', 'verb', 'raw:entry_4dffa7fb662d34fa664795f3', 'kaikki-plwiktionary');
INSERT OR IGNORE INTO dictionary_senses (id, lexeme_id, sense_order, usage_tags_json) VALUES ('sense_bd574cd80c059b2643e7caa5', 'lex_bd574cd80c059b2643e7caa5', 1, '[]');
INSERT OR IGNORE INTO dictionary_translations (sense_id, target_language, translation, translation_order, source_id) VALUES ('sense_bd574cd80c059b2643e7caa5', 'pl', 'zapłacić', 1, 'kaikki-plwiktionary');
INSERT OR IGNORE INTO dictionary_lexemes (id, source_language, lemma, normalized_lemma, part_of_speech, source_entry_id, source_id) VALUES ('lex_84ce6792700b81ae43f9b3d9', 'uk', 'повторяти', 'повторяти', 'verb', 'raw:entry_2f74ee7a5b5fdb75a94ac5ab', 'kaikki-plwiktionary');
INSERT OR IGNORE INTO dictionary_senses (id, lexeme_id, sense_order, usage_tags_json) VALUES ('sense_84ce6792700b81ae43f9b3d9', 'lex_84ce6792700b81ae43f9b3d9', 1, '[]');
INSERT OR IGNORE INTO dictionary_translations (sense_id, target_language, translation, translation_order, source_id) VALUES ('sense_84ce6792700b81ae43f9b3d9', 'pl', 'powtarzać', 1, 'kaikki-plwiktionary');

PRAGMA optimize;
